## Homework 4

<!--
Remember you can use the example4.Rmd or other files to find examples
of the codes you'll need to use to complete this assignment. I strongly
urge you to copy and paste relevant code that you know works from my
examples or instructions and then edit that code so you're working
with the appropriate variables for the homework.
-->

<!--
Set the working directory.
No Rchunk is needed to accomplish this.
-->
Set the location of the working files.
```{r}
setwd("~/Documents/PSY441/CapstoneReproducibility/04 Chi-Square Tests")
```

<!--
Read in the homework4.csv data. For each of the following steps you
should preface your R commands with some plain English explanation.
-->
Load in the data.
```{r}
dat<-read.csv("example4.csv")
```



<!--
Check the structure of the data.
-->
Look at the structure of the data.
```{r}
str(dat)
```

<!--
Create a table that shows how many people fell into each category.
-->
Create a table by category.
```{r}
table(dat$major, dat$gender)
```

<!--
Perform a chi-square test to determine whether or not the experimental
conditions and agreement with a statement are independent or related.
Also, interpret the results of your test and provide a a statistical
statement that supports your interpretation. As there's no way to
insert the chi-square symbol, you can just use chi-square instead
(see example4.Rmd).
-->
Perform a chi-square test to determine if the conditions are dependent or independent. 
```{r}
chisq.test(dat$major,dat$gender)
```
####Interpretation####
According to the results of the chi-square test, major and gender are independent of one another Chi-square(1) = 2.4, p = .12.